version: "3.8"

services:
  app:
    image: verovkind/flaskapp:latest
    command: guinicorn --bing :8000 --workers 3 -t 60 flask.wsgi:application
    restart: always
    ports:
      - "4200:4200"
    depends_on:
      - database
    env_file:
      - .env
    networks:
      - broker_network
      - nginx_network

  database:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=robot
      - POSTGRES_PASSWORD=robot
      - POSTGRES_DB=robot

  broker:
    image: redis:6.0.4-alpine
    networks:
      - broker_network
    volumes:
      - broker_data:/data

  celery_worker:
    image: verovkind/flaskapp:latest
    command: celery -A robot worker
    restart: always
    depends_on:
      - database
    env_file:
      - .env
    networks:
      - broker_network

  celery_beat:
    image: verovkind/flaskapp:latest
    command: celery -A robot beat
    restart: always
    depends_on:
      - database
    env_file:
      - .env
    networks:
      - broker_network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - nginx_network
    depends_on:
      - app

networks:
  broker_network:
    name: broker_network
    driver: bridge
  nginx_network:
    name: nginx_network
    driver: bridge

volumes:
  postgres_data:
  broker_data: