# Generated by Django 4.2 on 2023-04-15 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='purchase',
            table='purchase',
        ),
    ]
