# Generated by Django 4.2 on 2023-04-15 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_alter_purchase_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-date']},
        ),
    ]
